### ISSUE TITLE
Move to latest 3.1.3 release of neo4j libraries

### ISSUE THREAD

**Issue by dhakehurst** [datanucleus/datanucleus-neo4j#26]
the latest release of neo4j is 3.1.3.

if I use the datanucleus conector in my code, I cannot use the neo4j tools to view the same data, because datanucleus-neo4j uses an older (incompatible) version of the libraries.

1) create DB via datanucleus-neo4j
2) view data using neo4j 3.1.3
3) attempt to reconnect using datanucleus-neo4j

**Comment by andyjefferson** [comment]
If I run any test case manually specify the maven dependency 
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j</artifactId>
    <version>3.1.3</version>
</dependency>

they all run fine with current DN codebase. Also a plain rebuild against 3.1.3 requires zero changes to DN code. Consequently I can't see the need to do anything here. Did you simply not specify the neo4j dependency and rely on Maven dependency resolution to pull in 3.0.0 ? in which case specify 3.1.3 in your POM

**Comment by dhakehurst** [comment]
no I did not specify the neo4j version
(and I am using gradle not maven)

but seeing as this library has an explicit dependency on neo4j....why can I not rely on the transitive dependencies.

and the version of neo4j is explicitly set in this librabry, via a property. If we are expected to add our own dependency to a different version of neo4j, then the maven dependency should be marked as "provided" scope.

**Comment by andyjefferson** [comment]
No interest in making it provided. The way we have it, if a user wants to not specify it they get 3.0.0, and if they want to specify it then they get the version they ask for. Further than that people can easily contribute PULL REQUESTs

**Comment by andyjefferson** [comment]
User can easily use 3.x later versions by specifying it, and by default getting what the DN plugin is built against. Hence nothing to do here
