### ISSUE TITLE
Load of query doesnt ensure that all SCOs are wrapped

### ISSUE THREAD

**Issue by dhakehurst** [datanucleus/datanucleus-neo4j#28]
The closed bug https://github.com/datanucleus/datanucleus-neo4j/issues/27, is actually caused by the @Persistent annotation having defaultFetchGroup property set to "true".

see test "RelatedObjectNotPersisted" in https://github.com/dhakehurst/test-jdo

**Comment by andyjefferson** [comment]
If you actually debug it the problem is nothing to do with non-persistence (which is just a consequence), and actually down to the loaded List from the query is not a "wrapped" version (so cannot detect objects being added to the List).
