### ISSUE TITLE
Support for missing (non-String) columns in Neo4j database.

### ISSUE THREAD

**Issue by hopecee** [datanucleus/datanucleus-neo4j#33]
Hi!
I have already asked this question on StackOverflow [here](https://stackoverflow.com/questions/47978052/how-to-add-property-to-neo4j-database-table-that-contains-entry-datanucleus/47993364#47993364url). I think it will be beneficial to support missing (non-String) columns in Neo4j database. Because of this lack I have to discard the whole database whenever I want to add new non-String column to my model.

**Comment by andyjefferson** [comment]
Dup of #32
