### ISSUE TITLE
Creates new Object instead of setting it to another Object.

### ISSUE THREAD

**Issue by hopecee** [datanucleus/datanucleus-neo4j#34]
Hi!
A new Object is created whenever I try to set it to an object property. Let someone reproduce this. Is it the default behavior? 

    public class ProductClass implements Serializable {
        ...
        @PrimaryKey
        @Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
        long id;
        @Persistent
        private String name = null;
       ...
    }

    public class Product implements Serializable {
    ...
    @PrimaryKey
    @Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
    long id;
    @Persistent
    private String name = null;
    @Persistent(defaultFetchGroup = "true")
    private ProductClass productClass = null;
    ...
    }

Persisting the Product like this;

    Product prod = new Product();
    prod.setName('productName');
    prod.setProductClass(prodClass);

    PersistenceManager pm = JDOUtil.PERSISTENCE_MANAGER_FACTORY.getPersistenceManager();
    Transaction tx = pm.currentTransaction();
    try {
    tx.begin();
    pm.makePersistent(prod);
    Object id = pm.getObjectId(prod);
    tx.commit();
    } finally {
            if (tx.isActive()) {
                tx.rollback();
            }
            pm.close();
        }

Instead of setting the ProductClass to the Product, new ProductClass is produced.

**Comment by andyjefferson** [comment]
Attach a valid testcase following the template in the docs.

**Comment by hopecee** [comment]
Thanks @ andyjefferson.
This is what I am trying to create. I want to create Product data and each product has id, name and ProductClass.  I created two Tables, one for Product and the other for Product Class.
I first created list of ProductClass. To create Product , I have to set its ProductClass but I have been having some difficulties in achieving that.

**Comment by andyjefferson** [comment]
An issue tracker is not the place to ask questions! It is for reporting valid issues with valid testcases.

**Comment by hopecee** [comment]
Ok. I should take it to stackoverflow.
