### ISSUE TITLE
Ineqeulity Filter method, .ne() gives QueryExecutionException.

### ISSUE THREAD

**Issue by hopecee** [datanucleus/datanucleus-neo4j#35]
Hi.
I tried to execute a code like this, and I got a stack trace.

    JDOPersistenceManager jdopm = (JDOPersistenceManager) pm;
    QProductClass cand = QProductClass.candidate();
    JDOQLTypedQuery<Product> tq = jdopm.newJDOQLTypedQuery(Product.class);
    List<Product> prods = tq.filter(cand.name.ne(value)).executeList();

The stacktrace;

    Jan 03, 2018 8:01:14 PM com.hop.tub.servlets.TuListDataServlet doPost
    SEVERE: null
    org.neo4j.graphdb.QueryExecutionException: Unknown operation '!=' (you probably meant to use '<>',   which is the operator for inequality testing) (line 1, column 95 (offset: 94))
    "START this=node:DN_TYPES(class="com.hop.tub.neo4j.jdo.model.Product") WHERE (this.name != "ampiclox") RETURN this"
                                                                                           ^
    at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
    3at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:84)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:369)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:359)
    at org.datanucleus.store.neo4j.Neo4jUtils.executeCypherQuery(Neo4jUtils.java:319)

I am able to use equality and starts-with methods `.eq()`and `.startsWith()` respectively, but `.ne()` gives Exception.

I think this line explains the problem with the plugin.

    org.neo4j.graphdb.QueryExecutionException: Unknown operation '!=' (you probably meant to use '<>',   which is the operator for inequality testing) (line 1, column 95 (offset: 94))

**Comment by andyjefferson** [comment]
http://datanucleus.org/documentation/problem_reporting.html#jdo

**Comment by hopecee** [comment]
You can check my testcase [here](https://github.com/hopecee/test-jdo)

**Comment by hopecee** [comment]
@andyjefferson Thanks very much.
